on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install libcurl4
        run: sudo apt update && sudo apt install libcurl4-openssl-dev
        
      - name: Install JDK
        run: sudo apt install openjdk-21-jdk
        
      - name: Install terra dependencies
        run: sudo apt install libgdal-dev libgeos-dev libproj-dev
        
      - name: Install units dependencies
        run: sudo apt install libudunits2-dev
      
      - name: Install systemfonts dependencies
        run: sudo apt install libfontconfig1-dev
        
      - name: Install textshaping dependencies
        run: sudo apt install libharfbuzz-dev libfribidi-dev
      
      - name: Install PerformanceAnalytics dependencies
        run: sudo apt install gfortran

      - name: Install clipr dependencies
        run: sudo apt install libx11-dev
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
