on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: > 
          sudo apt update && sudo apt install 
          libcurl4-openssl-dev
          openjdk-21-jdk
          libgdal-dev libgeos-dev libproj-dev
          libudunits2-dev
          libfontconfig1-dev
          libharfbuzz-dev libfribidi-dev
      
        # Terra dependencies: libgdal-dev, libgeos-dev and libproj-dev
        # units dependencies: libudunits2-dev
        # systemfonts dependencies: libfontconfig1-dev
        # textshaping dependencies: libharfbuzz-dev libfribidi-dev
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
